{% set name = "bsplines2d" %}
{% set version = "0.0.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bsplines2d-{{ version }}.tar.gz
  sha256: 00ea3dcfbb7ded883ac160034b8e75e77d637dc73bdc122a9be6e09498cbed99

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=40.8.0
    - wheel
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy
    - matplotlib-base
    - datastock >=0.0.35

test:
  imports:
    - bsplines2d
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ToFuProject/bsplines2d
  summary: A python library for generic multidimensional bsplines on various meshes, using datastock
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Didou09
